config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  get 'landing/index'
  post 'landing/subscribes'

  constraints(subdomain: App.host('api')) do
    mount Sidekiq::Web => '/workers'
    mount ActionCable.server => "/cable"

    mount DefaultAPI, at: '/'
    mount GrapeSwaggerRails::Engine, at: '/explorer'
  end

  constraints(subdomain: App.host('admin'))  do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    root 'dashboard#index'

    resources :systems do
      collection do
        get '/', to: 'dashboard#index'
        get '/loot', to: 'dashboard#loot'

        resources :announcements
        resources :loots, only: [:index, :update]
        resources :ledgers
        resources :programs do
          put 'toggle_status', on: :member
        end

        resources :templates do
          member do
            get 'end_contest'
          end
          resources :questions do
            collection do
              get 'edit_all'
              put 'update_all'
            end
            member do
              put 'answer'
            end
            resources :answers
          end
          resources :contests
        end

        resources :prizes
        resources :promos

        get '/subscribes', to: 'users#subscribes'
        resources :users do
          get '/winners', to: 'users#winners'
          get '/contests', to: 'users#contests'
          get '/contests_show', to: 'user#contests_show'
          get '/transactions', to: 'users#transactions'
          get '/prizes', to: 'users#prizes'
          put '/prize_complete', to: 'users#prize_complete'
        end
        resources :gems
        resources :adverts do
          collection do
            get 'giveaways'
            post 'giveaways', to: 'adverts#giveaways_checked'
          end
        end

        resources :contests
      end
    end
  end

  constraints(subdomain: App.host(''))  do
    root 'landing#show'
  end

  constraints(subdomain: App.host('www'))  do
    root 'landing#show'
  end
end

app/models/announcement.rb
class Announcement
  include Mongoid::Document

  field :publish, type: DateTime
  field :description, type: String
  field :active, type: Boolean, default: true

  has_and_belongs_to_many :users, class_name: 'User', inverse_of: :announcements

  after_create :broadcast_opened
  after_save :edited
  # before_destroy :user_closed

  scope :active, -> { where(active: true) }

  validates :publish, :description, presence: true

  def broadcast_opened
    User.all.each do |user|
      self.users << user
      self.save!

      # ActionCable.server.broadcast("announcement_#{user.token}", announcement: user.announcements)
    end
  end

  def edited
    User.all.each do |user|
      # user.messages.create(message: self.description, publish_time: self.publish)
      # ActionCable.server.broadcast("announcement_#{user.token}", announcement: user.announcements)
    end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_announcement, only: :update

  def index
    @announcements = Announcement.active
    @announcement = Announcement.new
  end

  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      # if @announcement.save
      #   format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
      #   format.json { render :show, status: :created, location: @announcement }
      # else
      #   format.html { render :new }
      #   format.json { render json: @announcement.errors, status: :unprocessable_entity }
      # end
      @announcement.save
      format.html { redirect_to announcements_path, notice: 'Announcement was successfully created.' }
      format.json { render :show, status: :created, location: @announcement }
    end
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to announcements_path, notice: 'Announcement was successfully updated.' }
      #   format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
      #   format.json { render :show, status: :ok, location: @announcement }
      # else
      #   format.html { render :edit }
      #   format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.update(active: false)
    User.all.each do |user|
      user.announcements.delete(@announcement)
    end
    respond_to do |format|
        format.html { redirect_to announcements_path, notice: 'Announcement was successfully updated.' }
    #   format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
    #   format.json { head :no_content }
    end
  end

  private
   def set_announcement
      @announcement = Announcement.find(params[:id])
    end

   def announcement_params
      params.require(:announcement).permit(:publish, :description)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(announcement) do |f| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group"> <label class="control-label">Publish at</label>
    <%= f.text_field :publish, class: 'form-control', id: "announcement_datetimepicker" %>
  </div>
  <div class="form-group"> <label class="control-label">Announcement</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/_message.html.erb
<tr>
  <td><%= message.description %></td>
</tr>

app/views/announcements/edit.html.erb
<% content_for :body_id, 'announcement' %>

<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Editing Announcement <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>

    <%#= link_to 'Show', @announcement, class: 'btn btn-primary btn-sm rounded-s' %>
    <%= link_to 'Back', announcements_path, class: 'btn btn-primary btn-sm rounded-s' %>

    <section class="section">
      <div class="row sameheight-container">
        <div class="col-md-12">
        <div class="panel-body hidden" id="messages"></div>
          </div>
            <div class="col-md-8">
              <div class="card card-block sameheight-item">

                <%= form_for(@announcement, url: announcement_path(@announcement), html: { method: :put }) do |f| %>
                <% if @announcement.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

                      <ul>
                      <% @announcement.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div class="form-group"> <label class="control-label">Publish at</label>
                    <%= f.text_field :publish, class: 'form-control', id: "announcement_datetimepicker" %>
                  </div>
                  <div class="form-group"> <label class="control-label">Announcement</label>
                    <%= f.text_area :description, class: 'form-control' %>
                  </div>

                  <div class="actions">
                    <%= f.submit %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </section>
</article>

app/views/announcements/index.html.erb
<% content_for :body_id, 'announcement' %>

<article class="content forms-page">

  <div class="title-block">
    <h1 class="title"> Announcements
    <%#= link_to 'Add New', new_ledger_path, class: 'btn btn-primary btn-sm rounded-s' %>
    </h1>
    <%#<p class="title-description"> When blocks aren't enough </p>%>
  </div>

  <section class="section">
      <div class="row sameheight-container">
        <div class="col-md-12">

    <div class="panel-body hidden" id="messages">
    </div>

        </div>

          <div class="col-md-6">
              <div class="card card-block sameheight-item">
                  <div class="title-block">
                      <h3 class="title"> New Announcement </h3>
                  </div>


                <%= render 'form', announcement: @announcement %>
              </div>
          </div>
          <div class="col-md-6">
              <div class="card card-block sameheight-item">
                  <div class="title-block">
                      <h3 class="title"> Previous Announcement </h3>
                  </div>

                  <table class="table">
                    <tbody>
                      <% @announcements.each do |announcement| %>
                        <tr>
                          <td><%= announcement.publish.try(:strftime, "%B %d, %Y %H:%M") || 'NULL' %></td>
                          <td><%= announcement.description || 'NULL' %></td>
                          <td class="center-center"><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
                          <td class="center-center"><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>
          </div>
      </div>
  </section>
</article>