config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  get 'landing/index'
  post 'landing/subscribes'

  constraints(subdomain: App.host('api')) do
    mount Sidekiq::Web => '/workers'
    mount ActionCable.server => "/cable"

    mount DefaultAPI, at: '/'
    mount GrapeSwaggerRails::Engine, at: '/explorer'
  end

  constraints(subdomain: App.host('admin'))  do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    root 'dashboard#index'

    resources :systems do
      collection do
        get '/', to: 'dashboard#index'
        get '/loot', to: 'dashboard#loot'

        resources :announcements
        resources :loots, only: [:index, :update]
        resources :ledgers
        resources :programs do
          put 'toggle_status', on: :member
        end

        resources :templates do
          member do
            get 'end_contest'
          end
          resources :questions do
            collection do
              get 'edit_all'
              put 'update_all'
            end
            member do
              put 'answer'
            end
            resources :answers
          end
          resources :contests
        end

        resources :prizes
        resources :promos

        get '/subscribes', to: 'users#subscribes'
        resources :users do
          get '/winners', to: 'users#winners'
          get '/contests', to: 'users#contests'
          get '/contests_show', to: 'user#contests_show'
          get '/transactions', to: 'users#transactions'
          get '/prizes', to: 'users#prizes'
          put '/prize_complete', to: 'users#prize_complete'
        end
        resources :gems
        resources :adverts do
          collection do
            get 'giveaways'
            post 'giveaways', to: 'adverts#giveaways_checked'
          end
        end

        resources :contests
      end
    end
  end

  constraints(subdomain: App.host(''))  do
    root 'landing#show'
  end

  constraints(subdomain: App.host('www'))  do
    root 'landing#show'
  end
end

app/views/templates/_form.html.erb
<%= form_for(template, html: { class: 'item' }) do |f| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card card-block">
    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Name: </label>
      <div class="col-sm-4">
        <%= f.text_field :name, class: 'form-control boxed' %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Program: </label>
      <div class="col-sm-10">
        <%= f.select :program,
                    options_for_select(@programs.pluck(:name, :id),
                    selected: @template.program_id),
                    class: 'c-select form-control boxed' %>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Number Questions: </label>
      <div class="col-sm-10">
        <%= f.select :number_questions,
                    options_for_select((2..30), @template.number_questions),
                    class: 'c-select form-control boxed' %>

      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Number Answers: </label>
      <div class="col-sm-10">
        <%= f.select :number_answers,
                    options_for_select((2..10), @template.number_answers),
                    class: 'c-select form-control boxed' %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Start Date & Time : </label>
      <div class="col-sm-4">
        <%= f.text_field :start_time, value: @template.start_time, class: "form-control", id: 'datetimepicker1' %>
      </div>

      </div>

    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> End Date & Time : </label>
      <div class="col-sm-4">
        <%= f.text_field :end_time, value: @template.end_time, class: "form-control", id: 'datetimepicker2' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit 'Submit', class: 'btn btn-primary btn-submit' %>
      </div>
    </div>
  </div>

<% end %>

app/views/templates/edit.html.erb
<% content_for :body_id, 'edit-template' %>

<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Editing Template <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Show', @template, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= link_to 'Back', templates_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= render 'form', template: @template %>
</article>

app/views/templates/index.html.erb
<style>
<%#.items-list-page .item-list .item-col.item-col-questions {
  text-align: left;
  width: auto;
  text-align: center;
  -webkit-flex-basis: 70px;
  -ms-flex-preferred-size: 70px;
  flex-basis: 71px;
}%>
</style>

<article class="content items-list-page">
  <div class="title-search-block">
    <div class="title-block">
      <div class="row">
        <div class="col-md-6">
          <h3 class="title">
            Templates
            <%= link_to 'Add New', new_template_path, class: 'btn btn-primary btn-sm rounded-s' %>
          </h3>
        </div>
      </div>
    </div>

    <div class="items-search">
      <form class="form-inline">
        <div class="input-group">
          <input type="text" class="form-control boxed rounded-s" placeholder="Search for..."> <span class="input-group-btn">
          <button class="btn btn-secondary rounded-s" type="button">
          <i class="fa fa-search"></i>
          </button>
          </span>
        </div>
      </form>
    </div>
  </div>

  <h3>Template Active</h3>
  <div class="card items">
    <ul class="item-list striped">
      <li class="item item-list-header hidden-sm-down">
        <div class="item-row">
          <div class="item-col item-col-header item-col-title">
            <div> <span>Name</span> </div>
          </div>
          <div class="item-col item-col-header item-col-stats">
            <div class="no-overflow"> <span>Program</span> </div>
          </div>
          <div class="item-col item-col-header item-col-sales">
            <div class="no-overflow"> <span>Question</span> </div>
          </div>
          <div class="item-col item-col-header item-col-stats">
            <div class="no-overflow"> <span>Answers</span> </div>
          </div>
          <div class="item-col item-col-header item-col-date">
            <div> <span>Start Time</span> </div>
          </div>
          <div class="item-col item-col-header item-col-date">
            <div> <span>End Time</span> </div>
          </div>
        </div>
      </li>
      <% @template_active.each do |template| %>
        <li class="item">
          <div class="item-row">
            <div class="item-col fixed pull-left item-col-title">
              <div class="item-heading">Name</div>
              <div>
                <%= link_to template do %>
                  <h4 class="item-title">
                    <%= template.try(:name) || template._id %>
                  </h4>
                <% end %>
              </div>
            </div>
            <div class="item-col item-col-stats">
              <div class="item-heading">Program</div>
              <div><%= template.program.name %></div>
            </div>
            <div class="item-col item-col-sales">
              <div class="item-heading">Question</div>
              <div><%= template.number_questions %></div>
            </div>
            <div class="item-col item-col-stats">
              <div class="item-heading">Answers</div>
              <div><%= template.number_answers %></div>
            </div>
            <div class="item-col item-col-date">
              <div class="item-heading">Published</div>
              <div class="no-overflow"> <%= template.start_time.try(:strftime, "%B %d, %Y %H:%M:%S") %> </div>
            </div>
            <div class="item-col item-col-date">
              <div class="item-heading">Published</div>
              <div class="no-overflow"> <%= template.end_time.try(:strftime, "%B %d, %Y %H:%M:%S") %> </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <h3>Template Expired</h3>
  <div class="card items">
    <ul class="item-list striped">
      <li class="item item-list-header hidden-sm-down">
        <div class="item-row">
          <div class="item-col item-col-header item-col-title">
            <div> <span>Name</span> </div>
          </div>
          <div class="item-col item-col-header item-col-sales">
            <div class="no-overflow"> <span>Question</span> </div>
          </div>
          <div class="item-col item-col-header item-col-stats">
            <div class="no-overflow"> <span>Answers</span> </div>
          </div>
          <div class="item-col item-col-header item-col-date">
            <div> <span>Start Time</span> </div>
          </div>
          <div class="item-col item-col-header item-col-date">
            <div> <span>End Time</span> </div>
          </div>
        </div>
      </li>
      <% @template_expired.each do |template| %>
        <li class="item">
          <div class="item-row">
            <div class="item-col fixed pull-left item-col-title">
              <div class="item-heading">Name</div>
              <div>
                <%= link_to template do %>
                  <h4 class="item-title">
                    <%= template.try(:name) || template._id %>
                  </h4>
                <% end %>
              </div>
            </div>
            <div class="item-col item-col-sales">
              <div class="item-heading">Question</div>
              <div><%= template.number_questions %></div>
            </div>
            <div class="item-col item-col-stats">
              <div class="item-heading">Answers</div>
              <div><%= template.number_answers %></div>
            </div>
            <div class="item-col item-col-date">
              <div class="item-heading">Published</div>
              <div class="no-overflow"> <%= template.start_time.try(:strftime, "%B %d, %Y %H:%M:%S") %> </div>
            </div>
            <div class="item-col item-col-date">
              <div class="item-heading">Published</div>
              <div class="no-overflow"> <%= template.end_time.try(:strftime, "%B %d, %Y %H:%M:%S") %> </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</article>

app/views/templates/new.html.erb
<% content_for :body_id, 'new-template' %>

<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Add new template <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Back', templates_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= render 'form', template: @template %>
</article>

app/views/templates/show.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Show Template <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Back', templates_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <div class="card card-block">

    <p>
      Name: <%= @template.name %>
    </p>
    <p>
      Questions: <%= @template.number_questions %>
    </p>
    <p>
      Answers: <%= @template.number_answers %>
    </p>
    <p>
      Start Time: <%= @template.start_time.try(:strftime, "%B %d, %Y %H:%M:%S") %>
    </p>
    <p>
      End Time: <%= @template.end_time.try(:strftime, "%B %d, %Y %H:%M:%S") %>
    </p>

    <%= link_to 'Edit Template', edit_template_path(@template) %>
  </div>

  <%= link_to 'Edit Questions & Answers', edit_all_template_questions_path(@template) %>
  <div class="card card-block">
    <% @template.questions.each_with_index do |question, question_index| %>
      <div class="row">
        <label class="col-sm-2 form-control-label text-xs-right"> Question: <%= question_index + 1 %> </label>
        <div class="col-sm-10">
          <%= question.name %>
        </div>
      </div>
      <% question.answers.each_with_index do |answer, answer_index| %>
        <div class="row">
          <div class="offset-sm-2 col-sm-9">
            <div class="form-group row">
              <label>
                <img src="<%= answer.attachment %>" style="width: 100px;height: 100px;">
                <input class="radio"
                       name="question-<%= question._id %>"
                       type="radio"
                       value="<%= answer._id %>"
                       <%= 'checked' if question.is_correct.to_s == answer._id.to_s %>>
                <span><%= answer.name %></span>
              </label>
            </div>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-9">
          <% if @template.active %>
            <div class="btn btn-primary btn-sm rounded-s pull-right"
                 onClick="answerQuestion('<%= @template._id %>', '<%= question._id %>')">
              Enter Question <%= question_index + 1 %>
            </div>
          <% else %>
            <div class="btn btn-primary btn-sm rounded-s pull-right disabled">
              End contest
            </div>
          <% end %>
        </div>
      </div>
      <hr />
    <% end %>
    <% if @template.active %>
      <div class="btn btn-primary btn-lg"
           onClick="endContest()">
        End contest
      </div>
    <% else %>
      <div class="btn btn-primary btn-lg disabled">
        End contest
      </div>
    <% end %>
  </div>
</article>

<script>

  function answerQuestion(template, question, answer){
    answer = $('input[name=question-'+ question +']:checked').val()
    if(answer == undefined){
      $.alert('Please select a answer of question!');
      return false;
    }

    $.confirm({
      title: 'Confirm!',
      // content: 'Simple confirm!',
      buttons: {
        confirm: function () {
          $.ajax({
            url: '/systems/templates/'+ template +'/questions/'+ question +'/answers/' + answer,
            type: 'PUT',
            success: function(result) {
              console.log(result);
              if(result.status == 'success'){
                $.alert(result.message);
              }else {
                $.alert(result.message);
              }
            }
          });
        },
        cancel: function () {
          $.alert('Canceled!');
        },
      }
    });
  }

  function endContest(){
    $.confirm({
      title: 'Confirm!',
      // content: 'Simple confirm!',
      buttons: {
        confirm: function () {

          $.ajax({
            url: '<%= end_contest_template_path(@template, format: :json) %>',
            type: 'GET',
            success: function(result) {
              console.log(result)
              if(result.active) {
                $.alert('Error can not end contest!');
              }
              else {
                location.reload();
              }
            },
            error: function(result) {
              console.log(result)
              $.alert('System errors!');
            }
          });
        },
        cancel: function () {
          $.alert('Canceled!');
        },
      }
    });
  }

</script>


<style>
  .col-md-offset-4 {
    margin-left: 33.33333333%;
  }
</style>