config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  get 'landing/index'
  post 'landing/subscribes'

  constraints(subdomain: App.host('api')) do
    mount Sidekiq::Web => '/workers'
    mount ActionCable.server => "/cable"

    mount DefaultAPI, at: '/'
    mount GrapeSwaggerRails::Engine, at: '/explorer'
  end

  constraints(subdomain: App.host('admin'))  do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    root 'dashboard#index'

    resources :systems do
      collection do
        get '/', to: 'dashboard#index'
        get '/loot', to: 'dashboard#loot'

        resources :announcements
        resources :loots, only: [:index, :update]
        resources :ledgers
        resources :programs do
          put 'toggle_status', on: :member
        end

        resources :templates do
          member do
            get 'end_contest'
          end
          resources :questions do
            collection do
              get 'edit_all'
              put 'update_all'
            end
            member do
              put 'answer'
            end
            resources :answers
          end
          resources :contests
        end

        resources :prizes
        resources :promos

        get '/subscribes', to: 'users#subscribes'
        resources :users do
          get '/winners', to: 'users#winners'
          get '/contests', to: 'users#contests'
          get '/contests_show', to: 'user#contests_show'
          get '/transactions', to: 'users#transactions'
          get '/prizes', to: 'users#prizes'
          put '/prize_complete', to: 'users#prize_complete'
        end
        resources :gems
        resources :adverts do
          collection do
            get 'giveaways'
            post 'giveaways', to: 'adverts#giveaways_checked'
          end
        end

        resources :contests
      end
    end
  end

  constraints(subdomain: App.host(''))  do
    root 'landing#show'
  end

  constraints(subdomain: App.host('www'))  do
    root 'landing#show'
  end
end

app/models/program.rb
class Program
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps

  has_many :templates

  field :name,      type: String
  field :category,  type: String
  field :active,    type: Boolean, default: false

  has_mongoid_attached_file :attachment
  validates_attachment :attachment, content_type: { content_type: /\Aimage\/.*\Z/ }

  scope :active,    -> { where(active: true) }
  scope :pending,   -> { where(active: false) }

  validates :name, :category, :attachment, presence: true

  def self.upcoming
    self.active.includes(:templates).select do |program|
      program.templates.upcoming_program.present?
    end
  end

  def self.live
    self.active.includes(:templates).select do |program|
      program.templates.live_program.present?
    end
  end

  def self.past
    self.active.includes(:templates).select do |program|
      program.templates.past_program.present?
    end
  end

  def upcoming_time
    # templates.upcoming_time
    ts = templates.active.where(:start_time.lte => Time.zone.now, :end_time.gte => Time.zone.now)

    min = nil
    ts.each do |template|
      min = template.end_time if min.nil? or template.end_time < min
      # p template.end_time
    end
    min
  end

  def contests
    templates.current_template.contests
  end

  def all_contests
    templates.sort_by(&:end_time).select { |template| template.contests }
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_program, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params.merge!(active: true))

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_status
    respond_to do |format|
      if @program.update(active: !@program.active)
        format.html { redirect_to programs_path, notice: 'Program was successfully updated.' }
        # format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        # format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      # params.fetch(:program, {})
      params.require(:program).permit(:name, :category, :active, :attachment)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(program, html: { class: 'item' }) do |f| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card card-block">
    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Name: </label>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control boxed' %>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right"> Category: </label>
      <div class="col-sm-10">
        <%= f.select :category,
          options_for_select([["Select Category", ""], "Talent", "Competition", "Dating", "Cooking", "Lifestyle", "Award"], selected: @program.category),
          class: 'c-select form-control boxed'
        %>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 form-control-label text-xs-right" for=""> Image: </label>
      <div class="col-sm-10">
        <%= f.file_field :attachment %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/programs/edit.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Editing Program <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Show', @program, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= link_to 'Back', programs_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= render 'form', program: @program %>
</article>

app/views/programs/index.html.erb
<article class="content items-list-page">
  <div class="title-search-block">
    <div class="title-block">
      <div class="row">
        <div class="col-md-6">
          <h3 class="title">
            Programs
            <%= link_to 'Add New', new_program_path, class: 'btn btn-primary btn-sm rounded-s' %>
          </h3>
        </div>
      </div>
    </div>

    <div class="items-search">
      <form class="form-inline">
        <div class="input-group">
          <input type="text" class="form-control boxed rounded-s" placeholder="Search for..."> <span class="input-group-btn">
          <button class="btn btn-secondary rounded-s" type="button">
          <i class="fa fa-search"></i>
          </button>
          </span>
        </div>
      </form>
    </div>
  </div>

  <section class="section">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-block">
            <section class="example">
              <div class="table-flip-scroll">
                <table class="table table-bordered table-hover flip-content">
                  <thead class="flip-header">
                    <tr>
                      <th>Status</th>
                      <th>Picture</th>
                      <th>Name</th>
                      <th>&nbsp;</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @programs.each do |program| %>
                      <tr class="odd gradeX">
                        <td class="center-center">
                          <%= link_to toggle_status_program_path(program), method: :put, data: { confirm: 'Are you sure?' } do %>
                            <% if program.active %>
                              <i class="fa fa-pause fa-3x" style="color: red"></i>
                            <% else %>
                              <i class="fa fa-play fa-3x" style="color: green"></i>
                            <% end %>
                          <% end %>
                        </td>
                        <td><%= image_tag program.attachment, width: 120, height: 120 %></td>
                        <td class="center-left"><%= program.name %></td>
                        <td class="center-center"><%= link_to 'Edit', edit_program_path(program) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </section>
</article>

app/views/programs/new.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Add new program <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Back', programs_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= render 'form', program: @program %>
</article>

app/views/programs/show.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Show program <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>


  <p>
    Name: <%= @program.name %>
  </p>
  <p>
    Category: <%= @program.category %>
  </p>
  <p>
    Status: <%= @program.active %>
  </p>
  <%= link_to 'Edit', edit_program_path(@program), class: 'btn btn-primary btn-sm rounded-s' %>
  <%= link_to 'Back', programs_path, class: 'btn btn-primary btn-sm rounded-s' %>
</article>