config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  get 'landing/index'
  post 'landing/subscribes'

  constraints(subdomain: App.host('api')) do
    mount Sidekiq::Web => '/workers'
    mount ActionCable.server => "/cable"

    mount DefaultAPI, at: '/'
    mount GrapeSwaggerRails::Engine, at: '/explorer'
  end

  constraints(subdomain: App.host('admin'))  do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    root 'dashboard#index'

    resources :systems do
      collection do
        get '/', to: 'dashboard#index'
        get '/loot', to: 'dashboard#loot'

        resources :announcements
        resources :loots, only: [:index, :update]
        resources :ledgers
        resources :programs do
          put 'toggle_status', on: :member
        end

        resources :templates do
          member do
            get 'end_contest'
          end
          resources :questions do
            collection do
              get 'edit_all'
              put 'update_all'
            end
            member do
              put 'answer'
            end
            resources :answers
          end
          resources :contests
        end

        resources :prizes
        resources :promos

        get '/subscribes', to: 'users#subscribes'
        resources :users do
          get '/winners', to: 'users#winners'
          get '/contests', to: 'users#contests'
          get '/contests_show', to: 'user#contests_show'
          get '/transactions', to: 'users#transactions'
          get '/prizes', to: 'users#prizes'
          put '/prize_complete', to: 'users#prize_complete'
        end
        resources :gems
        resources :adverts do
          collection do
            get 'giveaways'
            post 'giveaways', to: 'adverts#giveaways_checked'
          end
        end

        resources :contests
      end
    end
  end

  constraints(subdomain: App.host(''))  do
    root 'landing#show'
  end

  constraints(subdomain: App.host('www'))  do
    root 'landing#show'
  end
end

app/models/promo.rb
class Promo
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code,          type: String
  field :quantity,      type: Integer
  field :bonus,         type: Integer
  field :currency_unit, type: String
  field :expires_at,    type: DateTime

  has_many :users, class_name: 'User', inverse_of: :promo
  # scope :active, -> { where(active: true) }

  def amount
    case currency_unit
    when 'diamonds'
      bonus * 12500
    when 'emeralds'
      bonus * 2500
    when 'sapphires'
      bonus * 500
    when 'rubies'
      bonus * 100
    when 'coins'
      bonus
    end
  end

  def used
    users.count
  end

  def available
    quantity - users.count
  end

  def self.available?(code)
    promo = find_by(code: code)
    if promo
      promo.users.count < promo.quantity
    else
      false
    end
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:code, :quantity, :bonus, :currency_unit, :expires_at)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<% content_for :body_id, 'promo' %>

<%= simple_form_for(@promo, html: { class: 'item' }) do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :quantity %>
    <%= f.input :bonus %>
    <%= f.input :currency_unit, collection: App.currency_unit %>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= f.input :expires_at, input_html: { id: 'expires_datetimepicker' } %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Editing Promo <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Show', @promo, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= link_to 'Back', promos_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= render 'form', promo: @promo %>
</article>

app/views/promos/index.html.erb
<article class="content responsive-tables-page">

  <div class="title-block">
    <h1 class="title"> Promo Tables
    <%= link_to 'Add New', new_promo_path, class: 'btn btn-primary btn-sm rounded-s' %>
    </h1>
    <%#<p class="title-description"> When blocks aren't enough </p>%>
  </div>

  <section class="section">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-block">
            <div class="card-title-block">
              <h3 class="title"> Promo </h3>
            </div>
            <section class="example">
              <div class="table-flip-scroll">
                <table class="table table-bordered table-hover flip-content">
                  <thead class="flip-header">
                    <tr>
                      <th>Code</th>
                      <th>Quantity</th>
                      <th>Bonus</th>
                      <th>Expires</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @promos.each do |promo| %>
                      <tr>
                        <td><%= promo.code %></td>
                        <td><%= promo.quantity %></td>
                        <td>
                          <%= promo.bonus %> <%= currency_icon(promo.currency_unit) %>
                        </td>
                        <td><%= promo.expires_at.try(:strftime, "%B %d, %Y") %></td>
                        <td><%= link_to 'Show', promo %></td>
                        <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
                        <td><%= link_to 'Destroy', promo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </section>
</article>

app/views/promos/new.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Add new Promo <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>
  <%= link_to 'Back', promos_path, class: 'btn btn-primary btn-sm rounded-s' %>
  <%= render 'form', promo: @promo %>
</article>

app/views/promos/show.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      Show Promo <span class="sparkline bar" data-type="bar"></span>
    </h3>
  </div>

  <p>
    <strong>Code:</strong>
    <%= @promo.code %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= @promo.quantity %>
  </p>

  <p>
    <strong>Used:</strong>
    <%= @promo.used %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= @promo.available %>
  </p>

  <p>
    <strong>Bonus:</strong>
    <%= @promo.bonus %> <%= currency_icon(@promo.currency_unit) %>
  </p>

  <p>
    <strong>Expires:</strong>
    <%= @promo.expires_at.try(:strftime, "%B %d, %Y") %>
  </p>

  <%= link_to 'Edit', edit_promo_path(@promo), class: 'btn btn-primary btn-sm rounded-s' %>
  <%= link_to 'Back', promos_path, class: 'btn btn-primary btn-sm rounded-s' %>
</article>